# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e37960139601657c13618086ec6cfb4f509367798c364fe6ec27da1cbc90a212ebd994b646caae85f6698586ee41896fea2cd33c3013c35fa2d0e09da113ecf1

test:
  secret_key_base: 6dd0aa26160b9de10234ebb9d402076ca4a26de13875bc52dffecceaed5a0a4ddae915a4e4535d07ea4e57e14881436b988eddb90cc8b15d4ac89f92f51e3cc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
